version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app           # Mount toàn bộ mã nguồn
      - ./static:/app/static
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    command: flask run --host=0.0.0.0 --port=5000

  celery:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - .:/app
      - ./static:/app/static
      - ./uploads:/app/uploads
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
